### PR TITLE
Show window from all workspace & don't show minimized (and make options translatable)

### PR DESCRIPTION
**Pull request by alberic89**
Show windows from all workspace and don't show minimized windows. TODO: add option to configure these two things.

I think it can be a great addition to this extension. Other extension do this, but they are not compatible with this.

The next step is to add two checkboxes/slider to allow the user to disable or enable these functionalities. The two variable that can be changed to change the behavior of the extension are `show_minimized` and the variable `all_desktops` of class `OtherWindowSwitcherPopup`.

### CODE REVIEW

**Comment by alberic89** [comment]
So now, you can configure the options:
Window switcher configuration window

**Comment by alberic89** [comment]
And now, the configuration options can be translated.

**Comment by alberic89** [comment]
I think it is ready to merge, no more change seems to be needed.

**Comment by alberic89** [comment]
I have just added the French translation.

**Comment by tbepdb** [comment]
thank you for request and sorry for late response.
i does migrated all project to gitlab and forgot change in description. this options was added in last version
https://extensions.gnome.org/extension/6060/windowswitcher

**Pull request closed without merging**
